### PR TITLE
Update to XinGe v2.37

### PR DESCRIPTION
**Pull request by sinofool**
Updated jar file version and names.
Removed other platforms other than armeabi, which is not necessary according to Tencent's document, users need it should download it separately and add them manually.

### CODE REVIEW

**Comment by gengen1988** [comment]
Hi. Thanks for updates. There two problem about libs:

1. Both Cordova and XinGe doesn't need android-support-v4. It is native UI stuff;
2. Some lib (such as Baidu Geolocation) will automatic generate armeabi-v7a. Apps having armeabi-v7a do not load lib from armeabi, which will cause this lib crush when bootstrap (file not found in armeabi-v7a).

Could you please fix these.

**Comment by sinofool** [comment]
Since 2.37, v7a, mips and x86 binaries are providing in different directory.
It is possible to include all platform libraries, but this will also crash app about not finding .so files in x86 directory.
Including less file is better, it gives clear error message about libtpns*.so, not other dependent.

User will always need to handle this problem manually until cordova offer new feature about choosing platform. Document needs update.

**Comment by gengen1988** [comment]
OK. Since you insist on manually import native libs, it will be merged into a feature branch. Master branch merges until test passed.

**Comment by sinofool** [comment]
Thanks a lot.

**Comment by gengen1988** [comment]
Yes, you are right. v2.37 does need support v4 to show notification. Sorry for misleading.

**Pull request merged**
